# ansible/site.yml
---
- name: Configure application servers
  hosts: all
  become: yes 
  vars:
    app_env: "{{ lookup('env', 'ENVIRONMENT') | default('dev') }}"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    - name: Install common packages
      apt:
        name:
          - nginx
          - python3
          - python3-pip
          - git
        state: present
    
    - name: Install application dependencies
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - flask
        - requests
        - boto3
    
    - name: Configure environment-specific settings
      template:
        src: "templates/{{ app_env }}/app.conf.j2"
        dest: "/etc/nginx/sites-available/app.conf"
      notify: restart nginx
    
    - name: Enable and start services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - app-service

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted